### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by desterhuizen** [vudash/vudash-core#2]
I tried to create a new dashboard following the steps specified. 

1. npm install -g vudash
2. vudash create

The above generated the below error:
`
 Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> 
`

I installed fs-extra manually and it started working.

Please add fs-extra to the dependencies list.

**Comment by antony** [comment]
Nice catch @desterhuizen - not sure how that has happened! Will fix asap.

**Comment by antony** [comment]
Fixed in v2.1.2
